### ISSUE TITLE
docker entrypoint ?

### ISSUE THREAD

**Issue by RomainBertrand** [D641593/MixNet#12]
I was able to download the docker tar archive (which took a long time, as it is very large)
However, when I try to run it (using `docker run -it mix_net` there is an error saying "no command specified"
When I try to specify an entrypoint, such as "/usr/bin/bash", it says "unable to start container".
What is the entrypoint please?

**Comment by D641593** [comment]
Hi, I think it might be "/bin/bash".
After graduated I couldn't connect to the server I used to use so it was difficult to check.

BTW, I don't know much about docker.
Did I share my docker tar in the wrong way, causing it to be so big?
Please give me some tips.

**Comment by D641593** [comment]
The command is "bash" not "/bin/bash".
Sorry for giving the wrong answer.

**Comment by RomainBertrand** [comment]
No problem !
It seems to work now, thanks.

You shared the entire docker image, which works, but you could also share the `Dockerfile` you created the docker with, and maybe the `docker-compose.yml` file as well.
That way, everybody could rebuild the image on their own, without needing to download the entire image.
