### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lillekemiker** [D641593/MixNet#2]
Hi there,

Any chance that you could include licensing information with your code? Just to specify whether it can be forked, used for commercial use etc.
I don't know how familiar you are with licenses, but in case you're not, some examples of nice, permissive licenses are "Apache license 2.0" or "MIT".

Some more info on licenses on github:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by D641593** [comment]
Hi, my code is built based on existing open source code.
Therefore, I use the same license as the original project.
I've added the license to this project.
Thanks for bringing this to my attention.
