### ISSUE TITLE
Pretrained FSNet_S weight

### ISSUE THREAD

**Issue by hdnhan** [D641593/MixNet#3]
Thank you for your excellent work.
In your paper, you mention that you use version 3 which is `FSNet_S`, can you share its pre-trained weight?

**Comment by D641593** [comment]
Hi, I upload the pre-trained weight to Google drive. 
Here is the link. 
https://drive.google.com/drive/folders/1YAg10FzO9OMLV881YOSBdq0DickAzvws?usp=sharing

**Comment by nhanerc** [comment]
Thanks :)
