### ISSUE TITLE
Image size matters

### ISSUE THREAD

**Issue by nhanerc** [D641593/MixNet#5]
I tried different image sizes on a dense text image like a dictionary page. Here is the output:
`2048x2048` resolution:
![scan1](https://github.com/D641593/MixNet/assets/111977314/4f753e1a-193e-4eff-b277-c139669f4d34)

`1024x1024` resolution:
![scan](https://github.com/D641593/MixNet/assets/111977314/983d74fb-a150-4569-ad03-ee2aac9cf6cb)

This is an expected behavior?

**Comment by nhanerc** [comment]
The image is from https://github.com/open-mmlab/mmocr/blob/main/demo/demo_densetext_det.jpg

**Comment by D641593** [comment]
Hi, the weights are all trained on the scene text detection datasets.
If you want to apply it to dense text images, you need to retrain on it.
I think this is because the size of the text in the image is too small and is seen as noise in the scene text detection dataset.
